<?php

namespace core\user\controller;

class CartController extends BaseUser
{

    protected function inputData()
    {
        parent::inputData(); // TODO: Change the autogenerated stub

        $a=1;

    }

}