<?php

namespace core\user\controller;

use core\user\controller\BaseUser;

class CatalogController extends BaseUser
{

    protected function inputData()
    {
        parent::inputData(); // TODO: Change the autogenerated stub
    }

}